#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: Vinyl Cast # REQUIRED - Enter your app name
  ios_id: # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: tech.schober.vinylcast.playstore # Optional - Enter Android app id like: com.example.app

  icon: images/app-icon-512.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  #favicon: # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  screenshot: images/app-screen-1080x2160.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  # creator_twitter: @allenschober # uncomment if creator has a twitter account "@awesome-dev"
  #social_image: # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: Listen to vinyl records wirelessly. # Optional
marketing_desc: Vinyl Cast is an Android app used to wirelessly stream the audio of a vinyl record player (or any audio source for that matter) to Google Cast-enabled (Chromecast built-in) devices or groups.

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github: aschober/vinyl-cast
  facebook:
  twitter: allenschober
  pinterest:
  instagram:
  email: vinylcast@schober.tech
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: pixel-3-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
background_image: /images/backgrounds/steve-harvey-LUMT0EeNnjE-unsplash.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: Vinyl Cast # Optional - Enter your site title
description: Listen to vinyl records wirelessly. # Optional - Enter your site description
footer: Background by <a href="https://unsplash.com/@trommelkopf">Steve Harvey</a> on <a href="https://unsplash.com/">Unsplash</a>

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
